// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © impressiveLeop50557
// https://www.youtube.com/watch?v=7My1dT4nmNU
//@version=5
strategy("변동성돌파",overlay = true,initial_capital = 10000000,default_qty_type = strategy.percent_of_equity,default_qty_value = 100, process_orders_on_close = true)
start_time = input.time(timestamp("2020-01-01"),confirm = true)
end_time = input.time(timestamp("2022-10-24"),confirm = true)
is_in_time = time >= start_time and time <= end_time
length = high - low
k = input.float(0.5)
new_length = length * k
entry_price = close + new_length
plot(close,offset = 1,linewidth = 2,color = color.white)
plot(entry_price,offset = 1,linewidth = 2,color = color.yellow)

if is_in_time
    strategy.entry("매수",strategy.long, stop = entry_price) // 돌파하면 매수
    strategy.close("매수") // 차트(봉)이 마감하면 종료